export const SETUP_CHECKING = 'SETUP_CHECKING';
export const SETUP_COMPLETE = 'SETUP_COMPLETE';
export const SETUP_INCOMPLETE = 'SETUP_INCOMPLETE';

export const AWS_CONNECTION_CONNECTING = 'AWS_CONNECTION_CONNECTING';
export const AWS_CONNECTION_ESTABLISHED = 'AWS_CONNECTION_ESTABLISHED';
export const AWS_CONNECTION_FAILED = 'AWS_CONNECTION_FAILED';
